// Email source for the CYD dashboard.
//
// By default this reads the state file written by Hermes/BMO at
// ~/.hermes/dashboard/state.json. If the file does not exist yet, the API
// falls back to a deterministic friendly "nothing urgent" state so the ESP32
// dashboard keeps working while Hermes is offline.
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { homedir } from "node:os";
import { log } from "./logger";

export type EmailLatest = {
  from: string;
  subject: string;
  date: string;   // "09/06 09:31"
  reason: string; // why it matters (from the agent)
};

export type Bmo = {
  status: "ok" | "attention" | "urgent";
  message: string;
};

export type EmailBlock = {
  email: {
    important_count: number;
    urgent_count: number;
    latest: EmailLatest[];
  };
  bmo: Bmo;
};

type HermesDashboardState = Partial<EmailBlock> & {
  last_updated?: string;
};

const STATE_FILE = resolve(
  process.env.HERMES_DASHBOARD_STATE ?? `${homedir()}/.hermes/dashboard/state.json`,
);

const MAX_ITEMS = Number(process.env.EMAIL_MAX_SHOW ?? 5);

function fallbackBlock(message = "BMO ainda nao encontrou emails importantes."): EmailBlock {
  return {
    email: { important_count: 0, urgent_count: 0, latest: [] },
    bmo: { status: "ok", message },
  };
}

function asStatus(value: unknown, email: EmailBlock["email"]): Bmo["status"] {
  if (value === "ok" || value === "attention" || value === "urgent") return value;
  if (email.urgent_count > 0) return "urgent";
  if (email.important_count > 0) return "attention";
  return "ok";
}

function cleanString(value: unknown, maxLen: number): string {
  return String(value ?? "").replace(/[\r\n\t]+/g, " ").trim().slice(0, maxLen);
}

function normalizeEmailItem(item: unknown): EmailLatest | null {
  if (!item || typeof item !== "object") return null;
  const record = item as Record<string, unknown>;
  const subject = cleanString(record.subject, 96);
  const from = cleanString(record.from, 48);
  if (!subject && !from) return null;
  return {
    from: from || "Email",
    subject: subject || "Sem assunto",
    date: cleanString(record.date, 24),
    reason: cleanString(record.reason, 96),
  };
}

function normalizeState(raw: HermesDashboardState): EmailBlock {
  const rawEmail = raw.email ?? {};
  const latest = Array.isArray(rawEmail.latest)
    ? rawEmail.latest.map(normalizeEmailItem).filter((x): x is EmailLatest => Boolean(x)).slice(0, MAX_ITEMS)
    : [];

  const email = {
    important_count: Math.max(0, Number(rawEmail.important_count ?? latest.length) || 0),
    urgent_count: Math.max(0, Number(rawEmail.urgent_count ?? 0) || 0),
    latest,
  };

  const status = asStatus(raw.bmo?.status, email);
  const defaultMessage =
    status === "urgent"
      ? `Leleu, tem ${email.urgent_count} email urgente.`
      : status === "attention"
        ? `Leleu, tem ${email.important_count} email importante.`
        : "Tudo tranquilo, nada urgente.";

  return {
    email,
    bmo: {
      status,
      message: cleanString(raw.bmo?.message, 140) || defaultMessage,
    },
  };
}

// Returns the { email, bmo } block generated by Hermes/BMO.
export async function getEmailBlock(): Promise<EmailBlock> {
  if (!existsSync(STATE_FILE)) {
    log.info("EMAIL", `state file missing: ${STATE_FILE}`);
    return fallbackBlock();
  }

  try {
    const raw = JSON.parse(await readFile(STATE_FILE, "utf8")) as HermesDashboardState;
    const block = normalizeState(raw);
    log.debug(
      "EMAIL",
      `state file: imp=${block.email.important_count} urg=${block.email.urgent_count} status=${block.bmo.status}`,
    );
    return block;
  } catch (err) {
    log.error("EMAIL", `failed to read ${STATE_FILE}`, err);
    return fallbackBlock("BMO nao conseguiu ler o estado dos emails.");
  }
}

// The ESP32's "Ler todas" button cannot safely mark Gmail directly. Instead it
// acknowledges the dashboard by zeroing the local state. Hermes's next triage run
// will repopulate it if there are still important unread emails.
export async function markAllRead(): Promise<EmailBlock> {
  const block = fallbackBlock("Tudo lido no dashboard. BMO vai verificar de novo em breve.");
  const payload = JSON.stringify({ ...block, last_updated: new Date().toISOString() }, null, 2);
  const tmp = `${STATE_FILE}.tmp`;
  await mkdir(dirname(STATE_FILE), { recursive: true });
  await writeFile(tmp, payload, "utf8");
  await rename(tmp, STATE_FILE);
  log.info("EMAIL", `acknowledged dashboard emails in ${dirname(STATE_FILE)}`);
  return block;
}

export const dashboardStateFile = STATE_FILE;
